version: 2
jobs:
   build:
     docker:
       - image: ubuntu:latest
     steps:
       - checkout
       - run: sudo apt update && sudo apt install -y libgtk-3-dev build-essential gcc g++ pkg-config make hostapd
       - run: make && sudo make install
