version: 2
jobs:
   build:
     docker:
       - image: ubuntu:latest
     steps:
       - checkout
       - run: ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo Europe/Minsk > /etc/timezone
       - run: DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y libgtk-3-dev build-essential gcc g++ pkg-config make hostapd
       - run: make && make install
